name: Validate README Files
on:
  push:
    paths:
      - '**/README.md'
  pull_request:
    paths:
      - '**/README.md'
jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check README structure
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
